module.exports = {
    "preset": "jest-puppeteer",
    "testEnvironment": "puppeteer",
    "testMatch": [
        "<rootDir>/src/**/?(*.)browserspec.{js,jsx,ts,tsx}"
    ],

    // The following is just copied from the jest file generated by `react-scripts eject`
    "collectCoverageFrom": [
      "src/{app,helpers}/**/*.{ts,tsx}"
    ],
    "transform": {
      "^.+\\.(js|jsx|ts|tsx)$": "<rootDir>/node_modules/babel-jest",
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$"
    ],
    "moduleFileExtensions": [
      "js",
      "ts",
    ]
}