Description: >
  Rex images for lambda runtimes 

Resources:

  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "rex"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          -
            Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::446683914483:user/tom"
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
Outputs:
  Repository:
    Description: The rex repo 
    Value:
      Fn::GetAtt: 'Repository.Arn'
    Export:
      Name: RexECRRepository
